### ISSUE TITLE
Fails to build on python 3.7

### ISSUE THREAD

**Issue by opoplawski** [crossbario/txaio#134]
```
+ coverage3 run -p --source=txaio /usr/bin/py.test-3.7 -s
============================= test session starts ==============================
platform linux -- Python 3.7.0, pytest-3.6.3, py-1.5.4, pluggy-0.6.0
rootdir: /builddir/build/BUILD/txaio-2.10.0, inifile:
plugins: cov-2.5.1
collected 66 items / 5 errors
==================================== ERRORS ====================================
___________________ ERROR collecting test/test_as_future.py ____________________
/usr/lib/python3.7/site-packages/_pytest/python.py:469: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:668: in _load_unlocked
    ???
<frozen importlib._bootstrap>:638: in _load_backward_compatible
    ???
/usr/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:226: in load_module
    py.builtin.exec_(co, mod.__dict__)
test/test_as_future.py:30: in <module>
    from util import run_once
E     File "/builddir/build/BUILD/txaio-2.10.0/test/util.py", line 60
E       def await(future):
E               ^
E   SyntaxError: invalid syntax
___________________ ERROR collecting test/test_call_later.py ___________________
/usr/lib/python3.7/site-packages/_pytest/python.py:469: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:668: in _load_unlocked
    ???
<frozen importlib._bootstrap>:638: in _load_backward_compatible
    ???
/usr/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:226: in load_module
    py.builtin.exec_(co, mod.__dict__)
test/test_call_later.py:34: in <module>
    from util import run_once
E     File "/builddir/build/BUILD/txaio-2.10.0/test/util.py", line 60
E       def await(future):
E               ^
E   SyntaxError: invalid syntax
____________________ ERROR collecting test/test_callback.py ____________________
/usr/lib/python3.7/site-packages/_pytest/python.py:469: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:668: in _load_unlocked
    ???
<frozen importlib._bootstrap>:638: in _load_backward_compatible
    ???
/usr/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:226: in load_module
    py.builtin.exec_(co, mod.__dict__)
test/test_callback.py:29: in <module>
    from util import run_once
E     File "/builddir/build/BUILD/txaio-2.10.0/test/util.py", line 60
E       def await(future):
E               ^
E   SyntaxError: invalid syntax
____________________ ERROR collecting test/test_errback.py _____________________
/usr/lib/python3.7/site-packages/_pytest/python.py:469: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:668: in _load_unlocked
    ???
<frozen importlib._bootstrap>:638: in _load_backward_compatible
    ???
/usr/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:226: in load_module
    py.builtin.exec_(co, mod.__dict__)
test/test_errback.py:29: in <module>
    from util import run_once
E     File "/builddir/build/BUILD/txaio-2.10.0/test/util.py", line 60
E       def await(future):
E               ^
E   SyntaxError: invalid syntax
_____________________ ERROR collecting test/test_gather.py _____________________
/usr/lib/python3.7/site-packages/_pytest/python.py:469: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
/usr/lib/python3.7/site-packages/py/_path/local.py:668: in pyimport
    __import__(modname)
E     File "/builddir/build/BUILD/txaio-2.10.0/test/test_gather.py", line 29
E       from util import await
E                            ^
E   SyntaxError: invalid syntax
!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 5 error in 3.93 seconds ============================
```
I believe this is because asyncio is now in python3.7.

**Comment by oberstet** [comment]
yeah, it's because "async/await" are actually real keywords beginning with 3.7 ..

**Comment by Jenselme** [comment]
@oberstet Can you provide a new release for that? I am packaging txaio for fedora and we are switching to Python 3.7. FYI: https://bugzilla.redhat.com/show_bug.cgi?id=1605971

**Comment by oberstet** [comment]
we should also add CI for 3.7: https://github.com/crossbario/txaio/blob/master/.travis.yml#L125

**Comment by eli-schwartz** [comment]
BTW we've solved this via a distro-side sed: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/python-txaio&id=9dea399b4c3ffbe856d0b2ce92e923b2409cd11e#n18

**Comment by oberstet** [comment]
@Jenselme fixed in the release I just pushed: v18.7.1

**Comment by eli-schwartz** [comment]
It builds, but the testsuite is still broken due to `asyncio.test_utils` moving to `test.test_asyncio.utils`...

**Comment by Jenselme** [comment]
Thanks!
